### ISSUE TITLE
Client Credentials Grant Type

### ISSUE THREAD

**Issue by tomasantunes** [neighbordog/deviantart#1]
There seems to be no option to use Client Credentials Grant Type on Deviantart's application registration.
![da-screenshot](https://cloud.githubusercontent.com/assets/12017352/15800585/12118a66-2a75-11e6-9f55-a2686f39e583.png)

**Comment by neighbordog** [comment]
I am terribly sorry for my late response. So basically you have to use the **Authorization Code** grant type when registering your application on DeviantArt. The credentials you then receive can be used to perform requests via the **Client Credentials** grant type.

For further informations take a look at : https://www.deviantart.com/developers/authentication

What endpoints support which grant types is described in the API documentation under here:
https://www.deviantart.com/developers/http/v1/20160316
