### ISSUE TITLE
Release 0.1.4 not available via pip.

### ISSUE THREAD

**Issue by zetasyanthis** [neighbordog/deviantart#3]
Strangely, pip doesn't seem to know about version 0.1.4 despite it showing up here: https://pypi.python.org/pypi/deviantart. This results in explosions in Python 3.5 for fixes that are present in 0.1.4, but not in 0.1.3. This has been tested with the base pip version available in Ubuntu 16.04, as well as the latest, 9.0.1.

```
zeta@zetaX220:~$ sudo -H pip3 install deviantart
Collecting deviantart
Requirement already satisfied: sanction in ./.local/lib/python3.5/site-packages (from deviantart)
Installing collected packages: deviantart
Successfully installed deviantart-0.1.3
```

**Comment by neighbordog** [comment]
Thanks for making me aware of this and sorry for the long delay. Should be resolved now.
