### ISSUE TITLE
/gallery/all endpoint?

### ISSUE THREAD

**Issue by nonamethanks** [neighbordog/deviantart#5]
I apologize if I'm simply blind and it was under my eyes all along, but I've been checking this module out and I can't figure a way to get https://www.deviantart.com/developers/http/v1/20160316/gallery_all/bdb19761e6debcc6609356d6b78f4a5d through it.

I don't see any mention of it in https://neighbordog.github.io/deviantart/deviantart.html - is this endpoint simply not included in this wrapper?

**Comment by theothersophie** [comment]
I think it's just `get_gallery_folder` (If you read the documentation it says it defaults to ALL)
